//! Runtime support for compile-time checked queries.
//!
//! The `query!()` macro generates a `CheckedQuery<T>` that holds the SQL,
//! encoded params, and a mapper function. The user calls `.fetch_all()`,
//! `.fetch_one()`, or `.fetch_opt()` to execute it.

use crate::encode::SqlParam;
use crate::error::TypedError;
use crate::query::Client;
use crate::row::Row;

/// A compile-time checked query ready for execution.
/// Generated by the `query!()` macro.
pub struct CheckedQuery<'a, T> {
    pub sql: &'a str,
    pub params: Vec<&'a dyn SqlParam>,
    pub _marker: std::marker::PhantomData<T>,
    pub mapper: fn(&Row) -> Result<T, TypedError>,
}

impl<'a, T> CheckedQuery<'a, T> {
    /// Execute and return all rows.
    pub async fn fetch_all(self, client: &Client) -> Result<Vec<T>, TypedError> {
        let rows = client.query(self.sql, &self.params).await?;
        rows.iter().map(self.mapper).collect()
    }

    /// Execute and return exactly one row.
    pub async fn fetch_one(self, client: &Client) -> Result<T, TypedError> {
        let row = client.query_one(self.sql, &self.params).await?;
        (self.mapper)(&row)
    }

    /// Execute and return an optional row.
    pub async fn fetch_opt(self, client: &Client) -> Result<Option<T>, TypedError> {
        let row = client.query_opt(self.sql, &self.params).await?;
        match row {
            Some(r) => Ok(Some((self.mapper)(&r)?)),
            None => Ok(None),
        }
    }
}

/// An unchecked query (no compile-time validation).
/// Generated by `query_unchecked!()`.
pub struct UncheckedQuery<'a> {
    pub sql: &'a str,
    pub params: Vec<&'a dyn SqlParam>,
}

impl<'a> UncheckedQuery<'a> {
    /// Execute and return raw rows.
    pub async fn fetch_all(self, client: &Client) -> Result<Vec<Row>, TypedError> {
        client.query(self.sql, &self.params).await
    }

    /// Execute and return exactly one row.
    pub async fn fetch_one(self, client: &Client) -> Result<Row, TypedError> {
        client.query_one(self.sql, &self.params).await
    }

    /// Execute and return an optional row.
    pub async fn fetch_opt(self, client: &Client) -> Result<Option<Row>, TypedError> {
        client.query_opt(self.sql, &self.params).await
    }

    /// Execute a statement (INSERT/UPDATE/DELETE), return affected row count.
    pub async fn execute(self, client: &Client) -> Result<u64, TypedError> {
        client.execute(self.sql, &self.params).await
    }
}
